version: "3.8"

services:
  rabbitmq:
    build:
      context: .docker/rabbitmq
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - ${AMQP_PORT}:5672 # default
      - ${MANAGEMENT_PORT}:15672 # management
      - ${STOMP_PORT}:15674 # web STOMP
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-${APP}"
      RABBITMQ_DEFAULT_USER: ${DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${DEFAULT_PASS}
